name: Test Build

on: 
    push: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        -   name: Install Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 20

        -   name: Install pnpm
            uses: pnpm/action-setup@v3
            with:
                version: 8

        -   name: Check out code
            uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

        -   name: Install dependencies
            run: pnpm install

        -   name: Build
            run: pnpm run build